language: c++

script: scons debug=1 && scons && scons debug=1 test=1 && scons test=1

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - eval "${MATRIX_EVAL}"

