language: c++

script: 
    - scons debug=1
    - scons debug=1 test=1 
    - scons 
    - scons test=1

matrix:
  include:
# OSX
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc5 && export CC=gcc-5 && export CXX=g++-5"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc6 && export CC=gcc-6 && export CXX=g++-6"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && export CC=gcc-7 && export CXX=g++-7"

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons ; fi

    - eval "${MATRIX_EVAL}"

